This is makeindex, version 2.18 [MiKTeX 26.2].
Scanning style file ./theoretical_perspectives.ist...........................done (27 attributes redefined, 0 ignored).
Scanning input file theoretical_perspectives.acn....done (304 entries accepted, 0 rejected).
Sorting entries.....done (2972 comparisons).
Generating output file theoretical_perspectives.acr....done (149 lines written, 0 warnings).
Output written in theoretical_perspectives.acr.
Transcript written in theoretical_perspectives.alg.
